### ISSUE TITLE
arcface model

### ISSUE THREAD

**Issue by garynlfd** [vuvko/fitw2020#3]
Hi, 

I tried to reproduce your training process but I encountered some problems.
Line 44, 45 in train.py, there's a .params and a .json files, but there's no such file in your repository.
I saw there's similar file in the folder "models" in your repository, but if I use those files I got some errors.
Is there any way to get those files used in line 44, 45?

Thanks!

**Comment by vuvko** [comment]
They're provided by the `insightface` package, but I don't quite remember the version. I believe it- was `0.18`. With that, you can download an `arcface` model.

**Comment by vuvko** [comment]
But everything should work with files from the `models` folder. If you've got errors, I believe it's due to the version of the `mxnet` package or something similar.

**Comment by garynlfd** [comment]
Sorry for the late reply.
Thank you for your reply!

**Comment by vuvko** [comment]
You're welcome, hope it helps!
